AddressBookApplication/AddressBookApplication/Controllers/EMailTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AddressBookApplication.Models;

namespace AddressBookApplication.Controllers
{
    public class EMailTypesController : Controller
    {
        private AddressBookDataEntities db = new AddressBookDataEntities();

        // GET: EMailTypes
        public ActionResult Index()
        {
            return View(db.EMailType.ToList());
        }

        // GET: EMailTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMailType eMailType = db.EMailType.Find(id);
            if (eMailType == null)
            {
                return HttpNotFound();
            }
            return View(eMailType);
        }

        // GET: EMailTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EMailTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EMailTypeId,Name")] EMailType eMailType)
        {
            if (ModelState.IsValid)
            {
                db.EMailType.Add(eMailType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eMailType);
        }

        // GET: EMailTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMailType eMailType = db.EMailType.Find(id);
            if (eMailType == null)
            {
                return HttpNotFound();
            }
            return View(eMailType);
        }

        // POST: EMailTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EMailTypeId,Name")] EMailType eMailType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eMailType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eMailType);
        }

        // GET: EMailTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMailType eMailType = db.EMailType.Find(id);
            if (eMailType == null)
            {
                return HttpNotFound();
            }
            return View(eMailType);
        }

        // POST: EMailTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EMailType eMailType = db.EMailType.Find(id);
            db.EMailType.Remove(eMailType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AddressBookApplication/AddressBookApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adresar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adresar", "Index", "Contacts", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kontakti", "Index", "Contacts")</li>
                    <li>@Html.ActionLink("Grupe kontakata", "Index", "ContactGroups")</li>
                    <li>@Html.ActionLink("Vrste telefonskih brojeva", "Index", "PhoneNumberTypes")</li>
                    <li>@Html.ActionLink("Vrste e-mail adresa", "Index", "EMailTypes")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>