AddressBookApplication/AddressBookApplication/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Contact))]
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.ContactEMail = new HashSet<ContactEMail>();
            this.ContactPhoneNumber = new HashSet<ContactPhoneNumber>();
            this.ContactGroup = new HashSet<ContactGroup>();
        }

        [DisplayName("ID kontakta")]
        public int ContactId { get; set; }
        [Required(ErrorMessage = "Obvezan podatak!")]
        [StringLength(50, ErrorMessage = "Tekst ne smije biti duži od 50 znakova!")]
        [DisplayName("Ime")]
        public string FirstName { get; set; }
        [StringLength(50, ErrorMessage = "Tekst ne smije biti duži od 50 znakova!")]
        [DisplayName("Prezime")]
        public string LastName { get; set; }
        [StringLength(50, ErrorMessage = "Tekst ne smije biti duži od 50 znakova!")]
        [DisplayName("Titula")]
        public string Title { get; set; }
        [StringLength(100, ErrorMessage = "Tekst ne smije biti duži od 100 znakova!")]
        [DisplayName("Kompanija")]
        public string Company { get; set; }
        [StringLength(300, ErrorMessage = "Tekst ne smije biti duži od 300 znakova!")]
        [DisplayName("Kućna adresa")]
        public string HomeAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactEMail> ContactEMail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPhoneNumber> ContactPhoneNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactGroup> ContactGroup { get; set; }
    }
}

AddressBookApplication/AddressBookApplication/ViewModels/AddGroupToContactViewModel.cs
using AddressBookApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AddressBookApplication.ViewModels
{
    [MetadataType(typeof(AddGroupToContactViewModel))]
    public class AddGroupToContactViewModel
    {
        [DisplayName("ID kontakta")]
        public int ContactId { get; set; }
        [DisplayName("Ime")]
        public string FirstName { get; set; }
        [DisplayName("Prezime")]
        public string LastName { get; set; }
        [DisplayName("Titula")]
        public string Title { get; set; }
        [DisplayName("Kompanija")]
        public string Company { get; set; }
        [DisplayName("Kućna adresa")]
        public string HomeAddress { get; set; }
        [DisplayName("ID grupe kontakata")]
        public int ContactGroupId { get; set; }
    }
}

AddressBookApplication/AddressBookApplication/Controllers/ContactEMailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AddressBookApplication.Models;

namespace AddressBookApplication.Controllers
{
    public class ContactEMailsController : Controller
    {
        private AddressBookDataEntities db = new AddressBookDataEntities();

        // GET: ContactEMails
        public ActionResult Index()
        {
            var contactEMail = db.ContactEMail.Include(c => c.Contact).Include(c => c.EMailType);
            return View(contactEMail.ToList());
        }

        // GET: ContactEMails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactEMail contactEMail = db.ContactEMail.Find(id);
            if (contactEMail == null)
            {
                return HttpNotFound();
            }
            return View(contactEMail);
        }

        // GET: ContactEMails/Create/1
        public ActionResult Create(int? contactId)
        {
            if (contactId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contact.Find(contactId);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = contactId;
            ViewBag.FirstName = contact.FirstName;
            ViewBag.LastName = contact.LastName;
            ViewBag.ContactTitle = contact.Title;
            ViewBag.Company = contact.Company;
            ViewBag.HomeAddress = contact.HomeAddress;
            ViewBag.EMailTypeId = new SelectList(db.EMailType, "EMailTypeId", "Name");
            return View();
        }

        // POST: ContactEMails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EMailId,ContactId,EMailTypeId,EMail,Default")] ContactEMail contactEMail)
        {
            if (ModelState.IsValid)
            {
                if (contactEMail.Default)
                {
                    var existingDefaultEMail = db.ContactEMail.Where(m =>
                        m.ContactId == contactEMail.ContactId
                        && m.Default).FirstOrDefault();

                    if (existingDefaultEMail != null)
                    {
                        existingDefaultEMail.Default = false;
                        db.Entry(existingDefaultEMail).State = EntityState.Modified;
                    }
                }
                else
                {
                    var existingEMail = db.ContactEMail.Where(m =>
                        m.ContactId == contactEMail.ContactId).FirstOrDefault();

                    if (existingEMail == null)
                    {
                        contactEMail.Default = true;
                    }
                }
                db.ContactEMail.Add(contactEMail);
                db.SaveChanges();
                return RedirectToAction("Edit", "Contacts", new { id = contactEMail.ContactId });
            }

            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactEMail.ContactId);
            ViewBag.EMailTypeId = new SelectList(db.EMailType, "EMailTypeId", "Name", contactEMail.EMailTypeId);
            return View();
        }

        // GET: ContactEMails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactEMail contactEMail = db.ContactEMail.Find(id);
            if (contactEMail == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactEMail.ContactId);
            ViewBag.EMailTypeId = new SelectList(db.EMailType, "EMailTypeId", "Name", contactEMail.EMailTypeId);
            return View(contactEMail);
        }

        // POST: ContactEMails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EMailId,ContactId,EMailTypeId,EMail,Default")] ContactEMail contactEMail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactEMail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactEMail.ContactId);
            ViewBag.EMailTypeId = new SelectList(db.EMailType, "EMailTypeId", "Name", contactEMail.EMailTypeId);
            return View(contactEMail);
        }

        // GET: ContactEMails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactEMail contactEMail = db.ContactEMail.Find(id);
            if (contactEMail == null)
            {
                return HttpNotFound();
            }
            return View(contactEMail);
        }

        // POST: ContactEMails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ContactEMail contactEMail = db.ContactEMail.Find(id);
            db.ContactEMail.Remove(contactEMail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AddressBookApplication/AddressBookApplication/Controllers/ContactPhoneNumbersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AddressBookApplication.Models;

namespace AddressBookApplication.Controllers
{
    public class ContactPhoneNumbersController : Controller
    {
        private AddressBookDataEntities db = new AddressBookDataEntities();

        // GET: ContactPhoneNumbers
        public ActionResult Index()
        {
            var contactPhoneNumber = db.ContactPhoneNumber.Include(c => c.Contact).Include(c => c.PhoneNumberType);
            return View(contactPhoneNumber.ToList());
        }

        // GET: ContactPhoneNumbers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactPhoneNumber contactPhoneNumber = db.ContactPhoneNumber.Find(id);
            if (contactPhoneNumber == null)
            {
                return HttpNotFound();
            }
            return View(contactPhoneNumber);
        }

        // GET: ContactPhoneNumbers/Create/1
        public ActionResult Create(int? contactId)
        {
            if (contactId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contact.Find(contactId);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = contactId;
            ViewBag.FirstName = contact.FirstName;
            ViewBag.LastName = contact.LastName;
            ViewBag.ContactTitle = contact.Title;
            ViewBag.Company = contact.Company;
            ViewBag.HomeAddress = contact.HomeAddress;
            ViewBag.PhoneNumberTypeId = new SelectList(db.PhoneNumberType, "PhoneNumberTypeId", "Name");
            return View();
        }

        // POST: ContactPhoneNumbers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhoneNumberId,ContactId,PhoneNumberTypeId,PhoneNumber,Default")] ContactPhoneNumber contactPhoneNumber)
        {
            if (ModelState.IsValid)
            {
                if (contactPhoneNumber.Default)
                {
                    var existingDefaultNumber = db.ContactPhoneNumber.Where(n =>
                        n.ContactId == contactPhoneNumber.ContactId
                        && n.Default).FirstOrDefault();

                    if (existingDefaultNumber != null)
                    {
                        existingDefaultNumber.Default = false;
                        db.Entry(existingDefaultNumber).State = EntityState.Modified;
                    }
                }
                db.ContactPhoneNumber.Add(contactPhoneNumber);
                db.SaveChanges();
                return RedirectToAction("Edit", "Contacts", new { id = contactPhoneNumber.ContactId });
            }

            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactPhoneNumber.ContactId);
            ViewBag.PhoneNumberTypeId = new SelectList(db.PhoneNumberType, "PhoneNumberTypeId", "Name", contactPhoneNumber.PhoneNumberTypeId);
            return View();
        }

        // GET: ContactPhoneNumbers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactPhoneNumber contactPhoneNumber = db.ContactPhoneNumber.Find(id);
            if (contactPhoneNumber == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactPhoneNumber.ContactId);
            ViewBag.PhoneNumberTypeId = new SelectList(db.PhoneNumberType, "PhoneNumberTypeId", "Name", contactPhoneNumber.PhoneNumberTypeId);
            return View(contactPhoneNumber);
        }

        // POST: ContactPhoneNumbers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhoneNumberId,ContactId,PhoneNumberTypeId,PhoneNumber,Default")] ContactPhoneNumber contactPhoneNumber)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactPhoneNumber).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContactId = new SelectList(db.Contact, "ContactId", "FirstName", contactPhoneNumber.ContactId);
            ViewBag.PhoneNumberTypeId = new SelectList(db.PhoneNumberType, "PhoneNumberTypeId", "Name", contactPhoneNumber.PhoneNumberTypeId);
            return View(contactPhoneNumber);
        }

        // GET: ContactPhoneNumbers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactPhoneNumber contactPhoneNumber = db.ContactPhoneNumber.Find(id);
            if (contactPhoneNumber == null)
            {
                return HttpNotFound();
            }
            return View(contactPhoneNumber);
        }

        // POST: ContactPhoneNumbers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ContactPhoneNumber contactPhoneNumber = db.ContactPhoneNumber.Find(id);
            db.ContactPhoneNumber.Remove(contactPhoneNumber);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AddressBookApplication/AddressBookApplication/Views/Contacts/AddGroupToContact.cshtml
@model AddressBookApplication.ViewModels.AddGroupToContactViewModel

@{
    ViewBag.Title = "Dodavanje kontakta u grupu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodavanje kontakta u grupu</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <hr />

        @Html.HiddenFor(model => model.ContactId)

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Company)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Company)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HomeAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HomeAddress)
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactGroupId, "Grupa kontakata", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ContactGroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <br /><br /><br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad na ažuriranje kontakta", "Edit", "Contacts", new { id = Model.ContactId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AddressBookApplication/AddressBookApplication/Views/Contacts/Create.cshtml
@model AddressBookApplication.Models.Contact

@{
    ViewBag.Title = "Novi kontakt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Novi kontakt</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad na listu", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AddressBookApplication/AddressBookApplication/Views/Contacts/Delete.cshtml
@model AddressBookApplication.Models.Contact

@{
    ViewBag.Title = "Brisanje kontakta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brisanje kontakta</h2>

<h3>Jeste li sigurni da želite obrisati ovaj kontakt?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Nazad na listu", "Index")
        </div>
    }
</div>

AddressBookApplication/AddressBookApplication/Views/Contacts/Edit.cshtml
@model AddressBookApplication.Models.Contact

@{
    ViewBag.Title = "Ažuriranje kontakta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ažuriranje kontakta</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContactId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>

        <h4>Telefonski brojevi</h4>

        <p>
            @if (Model.ContactPhoneNumber.Count < 6)
            {
                @Html.ActionLink("Novi telefonski broj", "Create", "ContactPhoneNumbers", new { contactId = Model.ContactId }, null)
            }
        </p>
        <table class="table">
            <tr>
                <th>
                    Vrsta
                </th>
                <th>
                    Broj
                </th>
                <th>
                    Zadano
                </th>
            </tr>

            @foreach (var item in Model.ContactPhoneNumber)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumberType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Default)
                    </td>
                </tr>
            }
        </table>

        <h4>E-mail adrese</h4>

        <p>
            @Html.ActionLink("Nova e-mail adresa", "Create", "ContactEMails", new { contactId = Model.ContactId }, null)
        </p>
        <table class="table">
            <tr>
                <th>
                    Vrsta
                </th>
                <th>
                    Adresa
                </th>
                <th>
                    Zadano
                </th>
            </tr>

            @foreach (var item in Model.ContactEMail)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMailType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Default)
                    </td>
                </tr>
            }
        </table>

        <h4>Povezane grupe kontakata</h4>

        <p>
            @Html.ActionLink("Dodaj kontakta u grupu", "AddGroupToContact", "Contacts", new { id = Model.ContactId }, null)
        </p>
        <table class="table">
            <tr>
                <th>
                    Naziv
                </th>
                <th>
                </th>
            </tr>

            @foreach (var item in Model.ContactGroup)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Detalji", "Details", "ContactGroups", new { id = item.ContactGroupId }, null)
                    </td>
                </tr>
            }
        </table>
    </div>
}

<div>
    @Html.ActionLink("Nazad na listu", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}